language: java
jdk:
- oraclejdk8
- openjdk8
script:
- jdk_switcher use oraclejdk8
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew build --scan -s"
- jdk_switcher use openjdk8
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew build --scan -s"
branches:
  only:
  - denis
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$PAGE_TOKEN"
  keep-history: true
  local-dir: public
  on:
    branch: master